CREATE DATABASE CA_MOCK_UP;
CREATE SCHEMA SALES;

create or replace TABLE RPR_ORDR_FC (
	REPAIR_ORDER_ID VARCHAR(500),
	VIN VARCHAR(25),
	CUSTOMER_ID VARCHAR(25),
	DEALER_ID VARCHAR(25),
	PART_ID VARCHAR(25),
	PRICE FLOAT,
	LABOR_HOURS FLOAT,
	REPAIR_DATE TIMESTAMP_NTZ(9),
	WARRANTY_FLAG BOOLEAN,
	constraint PK_RPR_ORDR_FC primary key (REPAIR_ORDER_ID)
);


create or replace TABLE CUSTOMER_DM (
	CUSTOMER_ID VARCHAR(50),
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	ZIPCODE VARCHAR(100),
	EMAIL VARCHAR(100),
	constraint PK_CUSTOMER primary key (CUSTOMER_ID)
);

create or replace TABLE DEALER_DM (
	DEALER_ID VARCHAR(50),
	NAME VARCHAR(100),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	ZIPCODE VARCHAR(100),
	PHONE_NUMBER VARCHAR(100),
	OPEN_DATE DATE,
	constraint PK_DEALER primary key (DEALER_ID)
);

create or replace TABLE PARTS_DM (
	PART_ID VARCHAR(50),
	NAME VARCHAR(100),
	MANUFACTURER VARCHAR(200),
	MANUFACTURE_DATE DATE,
	COST FLOAT,
	constraint PK_PART primary key (PART_ID)
);

create or replace TABLE VEHICLE_DM (
	VIN VARCHAR(25),
	MAKE VARCHAR(100),
	MODEL VARCHAR(100),
	YEAR NUMBER(4,0),
	MANUFACTURE_DATE DATE,
	TRIM VARCHAR(25),
	MSRP FLOAT,
	constraint PK_VEHICLE primary key (VIN)
);

ALTER ACCOUNT SET CORTEX_MODELS_ALLOWLIST = ALL;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CALL SNOWFLAKE.MODELS.CORTEX_BASE_MODELS_REFRESH();

SHOW MODELS IN SNOWFLAKE.MODELS;

